name: iconicmusic
publish_to: 'none'
version: 2.2.0

environment:
  sdk: ^3.5.4

dependencies:
  google_fonts: ^6.3.1
  just_audio: ^0.10.5
  http: ^1.5.0
  google_mobile_ads: ^6.0.0
  supabase_flutter: ^2.10.0
  sqflite: ^2.4.2
  audio_service: ^0.18.18
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  new_version_plus: ^0.1.1

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png